version: '3.4'

services:
  node:
    image: node
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8000
      DB_CONNECTION_URL: ${DB_CONNECTION_URL}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRECT_KEY: ${CLOUDINARY_SECRECT_KEY}
    ports:
      - "3000:8000"
