FROM node
WORKDIR /app
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY src/ src/
COPY server.ts server.ts
COPY .env .env
COPY tsconfig.json tsconfig.json
RUN npm install --force
ENTRYPOINT [ "npm","run","dev" ]



