FROM node:lts-alpine
ENV NODE_ENV=development
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --force
COPY . .
EXPOSE 3000
RUN chown -R node /usr/src/app
USER node
EXPOSE 8000
CMD ["npm", "run", "dev"]
