version: 1

services:
  - type: web
    name: webapp
    image: docker.io/majedur2377/webapp:27
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8000"
      - key: DB_CONNECTION_URL
        fromEnv: DB_CONNECTION_URL
      - key: JWT_SECRET
        fromEnv: JWT_SECRET
      - key: CLOUDINARY_NAME
        fromEnv: CLOUDINARY_NAME
      - key: CLOUDINARY_API_KEY
        fromEnv: CLOUDINARY_API_KEY
      - key: CLOUDINARY_SECRECT_KEY
        fromEnv: CLOUDINARY_SECRECT_KEY
    ports:
      - port: 8000
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: / # Adjust if your application has a specific health check endpoint
    region: oregon # Optional: choose the closest region to you
