version: 1

services:
  - type: web
    name: webapp
    dockerfilePath: ./Dockerfile # Path to your Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8000"
      - key: DB_CONNECTION_URL
        value: mongodb+srv://majed2377:majed2377@cluster0.vvvnn3j.mongodb.net/e-book10?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: ASDFGHJ344hjjj
      - key: CLOUDINARY_NAME
        value: derf19wfk
      - key: CLOUDINARY_API_KEY
        value: 286638696657847
      - key: CLOUDINARY_SECRECT_KEY
        value: lEf9BbRFV73lRt6B_WOySyCiAI0
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: / # Adjust if your application has a specific health check endpoint
    region: oregon # Optional: choose the closest region to you
