version: 1

services:
  - type: web
    name: webapp
    runtime: docker  # Specify the runtime as docker
    dockerfilePath: ./DockerFile # Path to your Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CONNECTION_URL
        value: mongodb+srv://majed2377:majed2377@cluster0.vvvnn3j.mongodb.net/e-book10?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: ASDFGHJ344hjjj
      - key: CLOUDINARY_NAME
        value: derf19wfk
      - key: CLOUDINARY_API_KEY
        value: 286638696657847
      - key: CLOUDINARY_SECRECT_KEY
        value: lEf9BbRFV73lRt6B_WOySyCiAI0
    autoDeploy: true
    plan: free  # Explicitly specify the free plan
    healthCheckPath: /
